trigger:
- 'main'

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  - group: publish-to-marketplace

steps:

- task: NodeTool@0
  inputs:
    versionSpec: 16.13.0
  displayName: 'Install Node.js'

- bash: |
    yarn && yarn generate
  displayName: Compile
- bash: |
    yarn deploy
  displayName: Publish
  env:
    VSCE_PAT: $(MARKETPLACE_MANAGE_JSM_ROBOT_PAT)
